export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const EDIT_USER = 'EDIT_USER';

export const CLEAR_PROJECT = 'CLEAR_PROJECT';
export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECT = 'GET_PROJECT';
export const ADD_PROJECT = 'ADD_PROJECT';
export const PROJECT_ERROR = 'PROJECT_ERROR';
export const RENAME_PROJECT = 'RENAME_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';

export const ADD_TASK = 'ADD_TASK';
export const EDIT_TASK = 'EDIT_TASK';
export const MOVE_TASK = 'MOVE_TASK';
export const CHANGE_TASK_STATUS = 'CHANGE_TASK_STATUS';
export const CHANGE_TASK_STORY_POINTS = 'CHANGE_TASK_STORY_POINTS';
export const ADD_TASK_MEMBER = 'ADD_TASK_MEMBER';
export const DELETE_TASK = 'DELETE_TASK';

export const START_SPRINT = 'START_SPRINT';
export const END_SPRINT = 'END_SPRINT';
export const EDIT_REVIEW_RETROSPECTIVE = 'EDIT_REVIEW_RETROSPECTIVE';

export const ADD_STATUS = 'ADD_STATUS';
export const EDIT_STATUS = 'EDIT_STATUS';
export const MOVE_STATUS = 'MOVE_STATUS';
export const CHANGE_STATUS_COLOR = 'CHANGE_STATUS_COLOR';
export const DELETE_STATUS = 'DELETE_STATUS';

export const ADD_MEMBER = 'ADD_MEMBER';
export const CHANGE_ROLE = 'CHANGE_ROLE';
export const LEAVE_PROJECT = 'LEAVE_PROJECT';
export const REMOVE_MEMBER = 'REMOVE_MEMBER';

// Sprint Plan Form
export const RESET_SPRINT_PLAN = 'RESET_SPRINT_PLAN';
export const SET_SPRINT_START = 'SET_SPRINT_START';
export const SET_SPRINT_END = 'SET_SPRINT_END';
export const SET_SPRINT_TARGET = 'SET_SPRINT_TARGET';
